# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode  
  pool: 6
  timeout: 5000
  username: karl
  password: ENV['DB_PASSWORD']

development:
  <<: *default
  database: fastlimo_development

test:
  <<: *default
  database: fastlimo_test

production:
  <<: *default
  database: fastlimo_production
